### ISSUE TITLE
data in the receipt-data property was malformed

### ISSUE THREAD

**Issue by mjpablo23** [gabrielgarza/monza#14]
I am getting this error when I try to follow the example to call Monza::Receipt.verify in Ruby: 

 2017-08-13 01:23:49 - Monza::VerificationResponse::VerificationError - The data in the receipt-data property was malformed.:

This is the line in the .rb file that causes the error:

response = Monza::Receipt.verify(data, options)

I get the base 64 encoded string with the following swift code: 

if let appStoreReceiptURL = Bundle.main.appStoreReceiptURL,
            FileManager.default.fileExists(atPath: appStoreReceiptURL.path) {
            do {
                let receiptData = try Data(contentsOf: appStoreReceiptURL, options: .alwaysMapped)
                let receiptString = receiptData.base64EncodedString(options: [])

Then I send the receiptString to the server.  What do I need to do to form the receipt data?

**Comment by mjpablo23** [comment]
I got past this error by getting the hard coded base64 string.  however, I am having trouble getting the response from Receipt.verify

**Comment by gabrielgarza** [comment]
@mjpablo23 this is the swift code you can use to get the base64 receipt string, and then send it to your server:

```swift
guard let receiptURL = Bundle.main.appStoreReceiptURL else {
     println(object: "no Bundle.main.appStoreReceiptURL")
     return
}

let receiptData = try Data(contentsOf: receiptURL)
let receiptDataBase64 = receiptData.base64EncodedString(options: Data.Base64EncodingOptions.endLineWithCarriageReturn)

// Send receiptDataBase64 to server

```
