### ISSUE TITLE
response from verify

### ISSUE THREAD

**Issue by mjpablo23** [gabrielgarza/monza#15]
when I call:  
response = Monza::Receipt.verify(data, options)

the response is nil.  is there something else I need to do?

**Comment by volkerholloh** [comment]
Hi,
did you set the options?

Your `data` string should contain about 6800 chars of the `receipt.data` your app should have send to your backend.
 
This is my code inside a job:

`

    options = { shared_secret: Rails.application.secrets.itunes_secret }
    begin
      response = Monza::Receipt.verify(data, options )
    rescue
      logger.error "Receipt verification failed with UserId: " + user.id.to_s
      return
    end

`

I hope this helps.

Cheers,
Volker

**Comment by mjpablo23** [comment]
Hi Volker, 
I am using the following code, but it still returns nil.  Is there any kind of waiting I need to do in Ruby for the response to come back?  I wouldn't expect it to have an instantaneous response, but I'm not sure how to do this in Ruby.
Thanks,
Paul

  puts "hardCoded receipt base64 string for monza: \n"  

  options = { shared_secret: "secretString" }

  begin 
    response = Monza::Receipt.verify(data, options)
    if (response == nil) 
  	puts "monza response is nil inside begin"
    else
  	puts "\n\nmonza response: " + response 
    end
  rescue 
  	logger.error "receipt verifcation failed with userId: " + senderId
  	return 
  end


------ output -------
monza response is nil

**Comment by volkerholloh** [comment]
Hi Paul,

your code looks ok to me.

Are you sure, your secret and data are working?

You could test is like this from the command line. But be aware that buy.itunes.apple.com is for production, otherwise it is: https://sandbox.itunes.apple.com/verifyReceipt

curl -d '{ "password":"`your_secret_key`" "receipt-data": "`data`"}' https://buy.itunes.apple.com/verifyReceipt

Cheers,
Volker

**Comment by mjpablo23** [comment]
Hi Volker,
Actually, I'm not sure how to set it to the sandbox URL in monza.  How do I
do that?  I think that is the problem.  I know that the secret and data is
correct.
Thanks,
Paul

**Comment by mjpablo23** [comment]
it looks like in receipt.rb, it is set as: 

 def self.verify(data, options = {})
      client = Client.production

so it will always use the production url.  

is it possible to change the code before installing the gem?

**Comment by mjpablo23** [comment]
oh ok, it looks like I need to do one of these: 
https://stackoverflow.com/questions/5515873/how-to-modify-a-ruby-gem

**Comment by volkerholloh** [comment]
No, actually Monza makes the switch when an error is returned. See https://github.com/gabrielgarza/monza/blob/master/lib/monza/receipt.rb, line 75. First, it calls the production endpoint at Apple, then, if the right error is returned, it calls the sandbox.

**Comment by mjpablo23** [comment]
ah I see, ok thanks.  yeah Monza still returns nil then.  I verified the receipt-data and password in Postman with the sandbox url.  If I use the production url, it returns error 21007.

**Comment by mjpablo23** [comment]
is "Rails.application.secrets.itunes_secret" in your code something that I should set?

**Comment by volkerholloh** [comment]
There is no need to. You set the secret by `options = { shared_secret: "secretString" }`. I fetch it as an application secret in my production code, security concerns and all. Those both ways should work.

**Comment by mjpablo23** [comment]
one thing I forgot to mention is that I am running the Ruby script remotely on a Heroku server.  Is there anything special I need to do to get Monza to work on it?  I logged into Heroku and did "gem install monza"

**Comment by volkerholloh** [comment]
You did `require 'monza'` in your script?

I would try to get the script running locally first, then progress to Heroku, but that's being me. :)

**Comment by gabrielgarza** [comment]
@mjpablo23 would you be able to share the Ruby code you are using? Is this a Ruby on Rails app?

If you are using a Rails app, you can include `gem 'monza'` in your gemfile and then run bundle install you should be good to go in terms on including the gem.

As @volkerholloh mentioned, running it locally first is a good practice. You can start the rails console by doing `rails console` in your terminal, and then run the following commands to see if it works:

``` ruby
data = "base64 receipt data string" # you can get this by using a breakpoint in xcode when you run through a test in app purchase
options = { shared_secret: "your shared secret" }
response = Monza::Receipt.verify(data, options)
```

**Comment by mjpablo23** [comment]
Hi Gabriel and Volker,

Here are the relevant parts of my Ruby script in Heroku.  The whole script has other parts that are not relevant.  I have included gem 'monza' in the gemfile.  

require 'monza'

post '/receiptValidation' do
  base64ReceiptDataString = params[:base64ReceiptDataString]
  senderId = params[:senderId]
  data = base64ReceiptDataString
  options = { shared_secret: "secretString" }
  begin
    response = Monza::Receipt.verify(data, options )
    if (response == nil) 
  	puts "response nil"
    else
      puts "response: " + response
    end
  rescue
    logger.error "Receipt verification failed with UserId: " + senderId
    return
  end
end

output on console:  response nil

I will try to run it locally first.  I had some trouble with my local packages so I was deploying directly to Heroku.  I will see if I can fix the package issues.

Thanks,
Paul

**Comment by gabrielgarza** [comment]
Hi Paul,

Would you be able to verify that you have a `base64ReceiptDataString` coming in from your parameters? It could be that you are passing in an empty string `""` or `nil` into the verify call.

For example `response = Monza::Receipt.verify("", shared_secret: SHARED_SECRET)` will return a `Monza::VerificationResponse::VerificationError` error and `response` will be `nil` in that case.

It's always best to test it locally first so you can easily catch errors:
1. Open terminal and type `irb` to open the ruby console.
2. `require 'monza'`
3.  `response = Monza::Receipt.verify(data, shared_secret: SHARED_SECRET)`

**Comment by mjpablo23** [comment]
Hi Gabriel,
I was able to verify that I am getting the correct base64ReceiptDataString, but I had to change all the space characters in it to '+'.  I'm not sure why I had to do that.  I've gotten Monza to run locally on my machine, and I can get the response from it.  I can call response.is_subscription_active and response.latest_expiry_date.  However, when I use Volker's code, I am still getting the message inside "rescue".  do you know why this is?

begin
  puts "Monza::Receipt.verify(data, options)"
  response = Monza::Receipt.verify(data, options)

  puts "volker response: "
  puts response

  puts "response.is_subscription_active: "
  puts response.is_subscription_active?

  puts "response.latest_expiry_date: "
  puts response.latest_expiry_date

  puts "response.latest_receipt_info.last.is_trial_period"
  puts response.latest_receipt_info.last.is_trial_period

  if (response == nil) 
    puts "volker response nil"
  else
    puts "volker response: " + response
  end
rescue
  puts "volker Receipt verification failed"
  return
end

******** output ********
volker response: 
#<Monza::VerificationResponse:0x007f9cdc3f3628>
response.is_subscription_active: 
false
response.latest_expiry_date: 
2017-08-12 22:15:27 UTC
response.latest_receipt_info.last.is_trial_period
false
volker Receipt verification failed

**Comment by mjpablo23** [comment]
it seems to work locally, but when I run the version in Heroku, the response is still nil

**Comment by gabrielgarza** [comment]
Good to hear its working for you now. I haven't tested it but it looks like you are adding a string and the response object here `puts "volker response: " + response` and that might be causing an error, so maybe do

`puts "volker response: "`
`puts response`

**Comment by mjpablo23** [comment]
ok thanks, that fixed the error.  This is just for the case when my rails app calls Receipt.verify with the data and secret.  The monza response is still nil after I deploy to Heroku and I try to connect with my iphone.  I'd like to test the response when rails is running on my computer.  Do you know how I should connect to rails running on my computer using my iphone?

**Comment by gabrielgarza** [comment]
Hey @mjpablo23 feel free to send me an email to garzagabriel@gmail.com

It's a bit tricky but you have to use something like xip.io and then in your info.plist add whatever URL  using xip.io  you use as an allowed domain

**Comment by mjpablo23** [comment]
Ah ok thanks, let me look into xip.io
