### ISSUE TITLE
cancellation_date does not exist in rubygem monza latest version 1.1.1

### ISSUE THREAD

**Issue by wmalik** [gabrielgarza/monza#16]
The following changes are not part of the latest version of monza on rubygems:
https://github.com/gabrielgarza/monza/commit/e2cd5712eff4279b0aa9ce0db4a5a2d51549e29f

**Comment by gabrielgarza** [comment]
@wmalik I just pushed out a new version 1.1.2 just to make sure. I tested it and `cancellation_date` is there for me. Let me know if you still experience issues.
