### ISSUE TITLE
silently ignoring errors

### ISSUE THREAD

**Issue by jjb** [gabrielgarza/monza#20]
First of all, thanks for a great, useful library!

I noticed here:

https://github.com/gabrielgarza/monza/blob/master/lib/monza/client.rb#L38

You are silently ignoring an exception. What's the rational here?

In such cases where I feel pretty confident it's okay, I will still log to STDOUT just in case something goes wrong and i want to audit logs later.

```ruby
rescue => e
  puts "error when blah blah: #{e.class}: #{e.message}
  nil
end
```

**Comment by gabrielgarza** [comment]
Hey @jjb thanks for using monza 👍 

Honestly I can't remember why I did not raise an exception here 🤔 any suggestion in mind? It's probably not even needed to be honest.

**Comment by jjb** [comment]
I would suggest not rescuing at all. The calling code can handle whatever errors show up.
