### ISSUE TITLE
Potential missing check for cancellation_date or inconsistency?

### ISSUE THREAD

**Issue by epetre** [gabrielgarza/monza#24]
Maybe there is a mistake or maybe I'm confused :). But the readme says that **is_any_subscription_active?** is helpful in the case the latest transaction was canceled. Assuming canceled means canceled by customer support, this implies that **is_subscription_active?** (checking the latest sub) would return **false** in the even that the latest transaction was canceled by customer support. But when looking in the code **is_subscription_active?** only checks for the expiry date, it doesn't check for a cancelation_date. This leads me to think that **is_subscription_active?** would still return true even if it was canceled by apple customer support and this would make **is_any_subscription_active?** useless.

Maybe I'm missing something but I think there is a missing check for **cancellation_date** in **is_subscription_active?**.

# From Docs:
```
Check if subscription is active
this checks if ANY transaction receipt expiry_date is in today or the future
this is helpful in case the most recent transaction was cancelled but the user still has a previous transaction or subscription that is active
response.is_any_subscription_active? # => true or false
```

**Comment by sidonath** [comment]
@epetre this check is missing indeed and we had a couple of issues with this as well. I'll submit a PR to address this issue tomorrow
