### ISSUE TITLE
Verification no longer works if grace period is not available

### ISSUE THREAD

**Issue by russellrichardson** [gabrielgarza/monza#27]
The grace period fields are optional, but commit https://github.com/gabrielgarza/monza/commit/f72358193834d1ae53deada319f634ec1490e369 assumes it will always be present.

With the grace period off the receipt verification returns nil. The parsing logic needs to confirm the fields are available.

**Comment by gabrielgarza** [comment]
@russellrichardson you are right. Fixing this now, will update soon

**Comment by gabrielgarza** [comment]
@russellrichardson Issue is now fixed in new version 1.3.6

See commit - https://github.com/gabrielgarza/monza/commit/775a0ca175f4b7624a1bc83a02a233325e2c58db

**Comment by russellrichardson** [comment]
@gabrielgarza thanks for the quick turn around, this gem has been very helpful!
