### ISSUE TITLE
CRITICAL BUG: `latest_expiry_date`, `is_subscription_active?` etc. are wrong

### ISSUE THREAD

**Issue by m-o-e** [gabrielgarza/monza#29]
Apple does **not** guarantee an order for the array in `@latest_receipt_info`.
`latest_receipt_info.last` is **not** guaranteed to return the newest receipt.

Monza must explicitly sort `@latest_receipt_info` by the respective timestamps
or things will break (we got bitten by this today 😢).

**Comment by samjohn** [comment]
we just got bitten by this as well!

**Comment by sidonath** [comment]
There is `Monza::VerificationResponse#is_any_subscription_active?` which can be used instead of `Monza::VerificationResponse#is_subscription_active?`. That method already checks the maximum `expired_date_ms` instead of the last one.

**Comment by benrugg** [comment]
Hi all - any update on this? I just realized how many of my users have been affected by this! I know there's some work going on with https://github.com/gabrielgarza/monza/pull/30. Any chance a hotfix can be pushed soon?

**Comment by gabrielgarza** [comment]
@benrugg the quickest hotfix you can do is use the `is_any_subscription_active?` method as @sidonath mentioned (see example in readme). 

I will also push the fix today and will update this thread when the new version of the gem is released.

**Comment by benrugg** [comment]
Thank you. I truly appreciate this gem and all your work!

**Comment by gabrielgarza** [comment]
Closing as this was fixed a while ago and forgot to close issue
