### ISSUE TITLE
Please cut a new release

### ISSUE THREAD

**Issue by m-o-e** [gabrielgarza/monza#6]
These changes have been committed half a year ago but never released:

https://github.com/gabrielgarza/monza/commit/de12a677df3b7751e3ec1e894903603470b59b2d

Monza can currently not be used in production
because it spams the log on every verification.

**Comment by gabrielgarza** [comment]
Hi @m-o-e I just released 0.1.3 in RubyGems which should include that commit. Thanks.

**Comment by m-o-e** [comment]
Perfect!  Thank you very much :)
