### ISSUE TITLE
any way of getting list of current paying customer?

### ISSUE THREAD

**Issue by matthieu80** [gabrielgarza/monza#7]
Hello,
I am about to use Monza in my project, it looks like a great gem so congrats and thank you for that!
I am wondering what could happen in the following edge case:
The customer pays a subscription, the receipt is sent from the mobile app to the server, but the server does not receive the receipt for whatever reason (server can be down, the device is offline...). The customer paid but the server is not aware of the changes...
Is there a way to get a list of receipts/paid customer from iTunes?
Or is it just something that has to be handled by the mobile? (keep the receipt in case of an error during the call to the server, re-try later on...)

Thank you very much!
Matt

**Comment by gabrielgarza** [comment]
Hi Matt,

I don't know of a way to get a list of receipts or paid customers from iTunes, don't think it's possible.

What I do is save the receipt data (bas64 string) locally in core data, and then send it to the server. Only when the server responds successfully I delete the object in core data. So in case the server fails, next time the user opens the app I check if there are any objects in core data that I need to retry sending  and I retry sending the receipt to the server.

**Comment by matthieu80** [comment]
ok, I'll do that.
Thank you Gabriel.
